services:
  bot:
    image: stefdp/discord-user-apps
    ports:
      - 3000:3000
    build: .
    container_name: discord-user-apps
    restart: unless-stopped
    environment:
      - BOT_TOKEN=
      - OWNERS= # user IDs split by "," example: 123,456,789
      - ZIPLINE_TOKEN=
      - ZIPLINE_URL=
      - ZIPLINE_CHUNK_SIZE=20
      - ZIPLINE_MAX_FILE_SIZE=1024
      - NAVIAC_USERNAME=
      - NAVIAC_TOKEN=
      - DASHBOARD_ENABLED=true
      - DASHBOARD_HOSTNAME=localhost
      - DASHBOARD_SECURE=false
      - DASHBOARD_URL_KEEP_PORT=true
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=
      - DISCORD_REDIRECT_URI=
      - JWT_SECRET=
    volumes:
      - ./data:/bot/data
      - ./permissions:/bot/src/data/permissions